# @package _group_

_name: top_level.debug.staircase.lm

criterion:
  _name: cross_entropy_with_ponder

common:
  _name: common.debug.staircase.lm
  no_progress_bar: true
  log_interval: 100
  seed: 1
  fp16: true
  # cpu: true

# this setup achieves ~28 ups with this on A100 half precision
model:
  _name: staircase_lm
  num_bottom_layers: 2
  num_staircase_layers: 2
  num_top_layers: 1
  share_decoder_input_output_embed: true
  position_encoding: xpos
  decoder:
      input_dim: 64
      output_dim: ${model.decoder.embed_dim}
      embed_dim: 64
      ffn_embed_dim: 256
      attention_heads: 8
      xformers_att_config: '{"name":"scaled_dot_product"}'


task:
  _name: chomsky_hierarchy
  task_name: "parity_check"

dataset:
  skip_invalid_size_inputs_valid_test: true
  required_batch_size_multiple: 1
  validate_interval: 2_500
  fixed_validation_seed: 1
  batch_size: 128
  num_workers: 2

optimizer:
  _name: adam
  weight_decay: 0.01

optimization:
  max_update: 100_000
  update_freq:
    - 1
  lr:
    - 3e-4
    # paper used {1,3,5}"e-4"

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 500

checkpoint:
  save_interval_updates: 2_500
  # keep_interval_updates_pattern: 5
  keep_interval_updates: 2
  keep_last_epochs: 0
  keep_best_checkpoints: -1
  no_save: false
  no_epoch_checkpoints: false
  no_last_checkpoints: false
  save_dir: ???
  # reset_dataloader: true
  # reset_optimizer: true
  # reset_lr_scheduler: true
  # reset_meters: true

hydra:
  job:
    name: hydra.debug.staircase.lm
